[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
faker = "^36.2.2"
python-dotenv = "^1.0.1"
httpx = "^0.28.1"
loguru = "^0.7.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
